jarvis: test-runner to track failures

diff --git a/jarvis b/jarvis
--- a/jarvis
+++ b/jarvis
@@ -207,7 +207,21 @@ case "${Action}" in
       exit 1
     fi
 
-    find ./tests -type f -executable -exec {} \;
+    result=0
+    mapfile -t test_files < <(find ./tests -type f -executable)
+
+    for test in "${test_files[@]}"; do
+        if ! "${test}" ; then
+            ((++result))
+        fi
+    done
+
+    if ((result > 0)); then
+        printf '%s test suites failed' "${result}" >&2
+        exit 1
+    else
+        exit 0
+    fi
     ;;
 
   --help | help)
